### ISSUE TITLE
Support for Rebus 6?

### ISSUE THREAD

**Issue by ThomasEg** [P47Phoenix/Rebus.AwsSnsAndSqs#2]
The current version of Rebus(v6) is not compatible with this library. Are this library still maintained and/or are there any plans for upgrading it to the latest version of Rebus?

**Comment by ThomasEg** [comment]
I've added a [PR](https://github.com/P47Phoenix/Rebus.AwsSnsAndSqs/pull/3), but i wasn't able to run the tests due to some missing AWS account....but i've tested the project via my project and it seems to be running now with Rebus 6....

**Comment by P47Phoenix** [comment]
Nice, I was looking to update it, however since you already did the work I will look at merging it in.
